=== sparrowzoo/sparrow-shell/sparrow-container/src/main/resources/beans.dtd
<!--
  ~ Licensed to the Apache Software Foundation (ASF) under one or more
  ~ contributor license agreements.  See the NOTICE file distributed with
  ~ this work for additional information regarding copyright ownership.
  ~ The ASF licenses this file to You under the Apache License, Version 2.0
  ~ (the "License"); you may not use this file except in compliance with
  ~ the License.  You may obtain a copy of the License at
  ~
  ~     http://www.apache.org/licenses/LICENSE-2.0
  ~
  ~ Unless required by applicable law or agreed to in writing, software
  ~ distributed under the License is distributed on an "AS IS" BASIS,
  ~ WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  ~ See the License for the specific language governing permissions and
  ~ limitations under the License.
  -->

        <!--
             MyEclipse config method:
             Preference->MyEclipse->Files and Editors->XML->
             XML Catalog->Add
             1)Location: .dtd file address
             2)Key Type: URI
             3)Key     : http://www.sparrowzoo.com/dtds/ioc.dtd
             DTD for the ioc Configuration File

             To support validation of your configuration file, include the following
             DOCTYPE element at the beginning (after the "xml" declaration):
            <!DOCTYPE beanFactory PUBLIC "-//sparrow Framework//DTD ioc Configuration//EN"
        "http://www.sparrowzoo.com/dtds/beanFactory.dtd">
             $Id: ioc.dtd$
             元素限定符用于在DTD中规定子元素出现的顺序和次数。
        常用的元素限定符有：

        () - 用来给元素分组;
        | - 在列出的元素中选择一个;
        + - 可出的元素至少出现1次（1或多次）;
        * - 列出的元素允许出现0次到任意多次（0或多次）;
        ? - 列出的元素出现0次或1次,;
        , - 列出的元素必须按照指定的顺序出现。
        -->
        <!ELEMENT beans (import|bean)*>
        <!ELEMENT bean (property|constructor-arg)*>
        <!ELEMENT import (#PCDATA)>
        <!ELEMENT property (#PCDATA)>
        <!ELEMENT constructor-arg (#PCDATA)>

        <!ATTLIST bean
                name   ID #REQUIRED
                alias CDATA #IMPLIED
                class    CDATA #REQUIRED
                controller (true|false) #IMPLIED
                interceptor (true|false) #IMPLIED
                interface    CDATA #IMPLIED
                scope (prototype|singleton) #IMPLIED
                remote (sparrow|dubble|rmi) #IMPLIED
                >



        <!ATTLIST property
                name CDATA #REQUIRED
                ref  CDATA #IMPLIED
                value  CDATA #IMPLIED
                placeholder CDATA #IMPLIED
                >

        <!ATTLIST constructor-arg
            index CDATA #REQUIRED
            name CDATA #REQUIRED
            ref  CDATA #IMPLIED
            value  CDATA #IMPLIED
            type CDATA #IMPLIED
            >

        <!ATTLIST import
                resource CDATA #REQUIRED
                >

=== sparrowzoo/sparrow-shell/sparrow-test/src/main/resources/sparrow_application_context.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE beans PUBLIC "-//sparrow Framework//DTD ioc Configuration//EN"
        "beans.dtd">
<beans>
    <component-scan>com.sparrow</component-scan>
    <!---当前进程的所有datasource实例-->
    <bean name="dataSourceFactory" class="com.sparrow.orm.datasource.DataSourceFactoryImpl">
        <constructor-arg index="1" name="initDatasourceKeys" value="sparrow_default" type="string"/>
    </bean>

    <bean name="connectionContextHolder" class="com.sparrow.orm.transaction.ConnectionContextHolderImpl">
        <property name="dataSourceFactory" ref="dataSourceFactory"/>
    </bean>

    <bean name="poolConfig" class="redis.clients.jedis.JedisPoolConfig">
        <property name="maxActive" value="${redis.pool.maxActive}"/>
        <property name="maxIdle" value="${redis.pool.maxIdle}"/>
        <property name="maxWait" value="${redis.pool.maxWait}"/>
        <property name="minIdle" value="${redis.pool.minIdle}"/>
        <property name="testOnBorrow" value="${redis.pool.testOnBorrow}"/>
        <property name="timeBetweenEvictionRunsMillis" value="${redis.pool.timeBetweenEvictionRunsMillis}"/>
        <property name="minEvictableIdleTimeMillis" value="${redis.pool.minEvictableIdleTimeMillis}"/>
    </bean>

    <bean name="redisPool" class="com.sparrow.cache.impl.redis.jedis.RedisPool">
        <property name="urls" value="${redis_url}"/>
        <property name="config" ref="poolConfig"/>
    </bean>


    <bean name="sparrow_default" class="com.sparrow.datasource.ConnectionPool">
        <property name="dataSourceFactory" ref="dataSourceFactory"/>
    </bean>

    <bean name="sparrowServletUtility" class="com.sparrow.utility.web.SparrowServletUtility"/>
    <bean name="authenticatorService" class="com.sparrow.authorizing.AuthenticatorDemo"/>
    <bean name="authorizerService" class="com.sparrow.authorizing.AuthorizerDemo"/>

    <bean name="helloController" class="com.sparrow.controller.HelloController" controller="true">
        <property name="authenticatorService" ref="authenticatorService"/>
        <property name="servletContainer" ref="sparrowServletContainer"/>
    </bean>
    <bean name="elasticSearchController" class="com.sparrow.controller.ElasticSearchController" controller="true"/>
    <bean name="classLoaderController" class="com.sparrow.controller.ClassLoaderController" controller="true"/>
</beans>

=== sparrowzoo/sparrow-shell/demo/sparrow-test/src/main/resources/sparrow_application_context.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE beans PUBLIC "-//sparrow Framework//DTD ioc Configuration//EN"
        "beans.dtd">
<beans>
    <!--    <import resource="sparrow-default-beans.xml"/>-->
    <component-scan>com.sparrow</component-scan>
    <import resource="sparrow-default-beans.xml"/>




    <bean name="poolConfig" class="redis.clients.jedis.JedisPoolConfig">
        <property name="maxActive" value="${redis.pool.maxActive}"/>
        <property name="maxIdle" value="${redis.pool.maxIdle}"/>
        <property name="maxWait" value="${redis.pool.maxWait}"/>
        <property name="minIdle" value="${redis.pool.minIdle}"/>
        <property name="testOnBorrow" value="${redis.pool.testOnBorrow}"/>
        <property name="timeBetweenEvictionRunsMillis" value="${redis.pool.timeBetweenEvictionRunsMillis}"/>
        <property name="minEvictableIdleTimeMillis" value="${redis.pool.minEvictableIdleTimeMillis}"/>
    </bean>

    <bean name="sparrow_default" class="com.sparrow.datasource.ConnectionPool">
        <property name="dataSourceFactory" ref="dataSourceFactory"/>
    </bean>

    <bean name="redisPool" class="com.sparrow.cache.impl.redis.jedis.RedisPool">
        <property name="urls" value="${redis_url}"/>
        <property name="config" ref="poolConfig"/>
    </bean>

    <bean name="authenticatorService" class="com.sparrow.authorizing.AuthenticatorDemo"/>
    <bean name="authorizerService" class="com.sparrow.authorizing.AuthorizerDemo"/>

    <bean name="helloController" class="com.sparrow.controller.HelloController" controller="true">
        <property name="authenticatorService" ref="authenticatorService"/>
        <property name="servletContainer" ref="sparrowServletContainer"/>
    </bean>
    <bean name="elasticSearchController" class="com.sparrow.controller.ElasticSearchController" controller="true"/>
    <bean name="classLoaderController" class="com.sparrow.controller.ClassLoaderController" controller="true"/>

    <bean name="authorizingService" class="com.sparrow.authorizing.AuthorizingDemo"/>
    <bean name="previewController" class="com.sparrow.markdown.controller.PreviewController" controller="true"/>
    <bean name="yamlController" class="com.sparrow.yaml.controller.YamlController" controller="true"/>
    <bean name="commendLineFormatController" class="com.sparrow.jvm.controller.CommendLineFormatController"
          controller="true"/>
</beans>

=== sparrowzoo/sparrow-shell/sparrow-test/src/test/resources/dao.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!--
  Licensed to the Apache Software Foundation (ASF) under one or more
  contributor license agreements.  See the NOTICE file distributed with
  this work for additional information regarding copyright ownership.
  The ASF licenses this file to You under the Apache License, Version 2.0
  (the "License"); you may not use this file except in compliance with
  the License.  You may obtain a copy of the License at

      http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.
  -->

<!DOCTYPE beans PUBLIC "-//sparrow Framework//DTD ioc Configuration//EN"
    "beans.dtd">
<beans>
    <component-scan>com.sparrow</component-scan>
    <bean name="dataSourceFactory" class="com.sparrow.datasource.DataSourceFactoryImpl">
        <constructor-arg index="1" name="initDatasourceKeys" value="user_default"/>
    </bean>
    <bean name="user_default" class="com.sparrow.datasource.ConnectionPool">
        <property name="dataSourceFactory" ref="dataSourceFactory"/>
    </bean>
    <!--必须定义，且必须为prototype-->
    <bean name="user" class="com.sparrow.orm.po.User" scope="prototype"/>
    <!--必须定义，且必须为prototype-->
    <bean name="event" class="com.sparrow.orm.po.Event" scope="prototype"/>
</beans>

=== sparrowzoo/sparrow-shell/demo/sparrow-test/src/test/resources/sparrow_rocketmq_consumer.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!--
  ~ Licensed to the Apache Software Foundation (ASF) under one or more
  ~ contributor license agreements.  See the NOTICE file distributed with
  ~ this work for additional information regarding copyright ownership.
  ~ The ASF licenses this file to You under the Apache License, Version 2.0
  ~ (the "License"); you may not use this file except in compliance with
  ~ the License.  You may obtain a copy of the License at
  ~
  ~     http://www.apache.org/licenses/LICENSE-2.0
  ~
  ~ Unless required by applicable law or agreed to in writing, software
  ~ distributed under the License is distributed on an "AS IS" BASIS,
  ~ WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  ~ See the License for the specific language governing permissions and
  ~ limitations under the License.
  -->

<!DOCTYPE beans PUBLIC "-//sparrow Framework//DTD ioc Configuration//EN"
    "beans.dtd">
<beans>
    <bean name="cacheMonitor" class="com.sparrow.redis.SparrowCacheMonitor"/>
    <bean name="redisPool" class="com.sparrow.cache.impl.redis.RedisPool">
        <property name="urls" value="127.0.0.1:6379"/>
        <property name="cacheMonitor" ref="cacheMonitor"/>
    </bean>

    <bean name="cacheClient" class="com.sparrow.cache.impl.redis.RedisCacheClient">
        <property name="redisPool" ref="redisPool"/>
    </bean>
    <bean name="mqIdempotent" class="com.sparrow.mq.DefaultIdempotent">
        <property name="cacheClient" ref="cacheClient"/>
    </bean>
    <bean name="messageConverter" class="com.sparrow.rocketmq.impl.SparrowJsonMessageConverter">
        <property name="charset" value="UTF-8"/>
    </bean>

    <bean name="distributedCountDownLatch" class="com.sparrow.concurrent.latch.impl.RedisDistributedCountDownLatch">
        <property name="cacheClient" ref="cacheClient"/>
    </bean>

    <bean name="queueHandlerMappingContainer" class="com.sparrow.mq.DefaultQueueHandlerMappingContainer"/>

    <bean name="rocketMQMessageListener" class="com.sparrow.rocketmq.impl.SparrowRocketMQMessageListener">
        <property name="messageConverter" ref="messageConverter"/>
        <property name="queueHandlerMappingContainer" ref="queueHandlerMappingContainer"/>
        <property name="mqIdempotent" ref="mqIdempotent"/>
        <property name="distributedCountDownLatch" ref="distributedCountDownLatch"/>
    </bean>



    <bean name="mqConsumer" class="com.sparrow.rocketmq.impl.RocketMQConsumer">
        <property name="groupName" value="sparrow-consumer-group"/>
        <property name="topicConfig" value="sparrow-test-topic:sparrow"/>
        <property name="messageListener" ref="rocketMQMessageListener"/>
        <property name="nameServerAddress" value="127.0.0.1:9876"/>
        <property name="cacheClient" ref="cacheClient"/>
        <property name="batchSize" value="100"/>
        <property name="pullSize" value="1000"/>
        <property name="pullInterval" value="10000"/>
        <property name="threadCount" value="2"/>
    </bean>

    <bean name="helloHandler" class="com.sparrow.rocketmq.protocol.handler.HelloWorldHandler">
        <property name="queueHandlerMappingContainer" ref="queueHandlerMappingContainer"/>
    </bean>
</beans>

=== sparrowzoo/sparrow-shell/demo/sparrow-test/src/test/resources/redis_config.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!--
  ~ Licensed to the Apache Software Foundation (ASF) under one or more
  ~ contributor license agreements.  See the NOTICE file distributed with
  ~ this work for additional information regarding copyright ownership.
  ~ The ASF licenses this file to You under the Apache License, Version 2.0
  ~ (the "License"); you may not use this file except in compliance with
  ~ the License.  You may obtain a copy of the License at
  ~
  ~     http://www.apache.org/licenses/LICENSE-2.0
  ~
  ~ Unless required by applicable law or agreed to in writing, software
  ~ distributed under the License is distributed on an "AS IS" BASIS,
  ~ WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  ~ See the License for the specific language governing permissions and
  ~ limitations under the License.
  -->

<!DOCTYPE beans PUBLIC "-//sparrow Framework//DTD ioc Configuration//EN"
        "beans.dtd">
<beans>
    <bean name="initializer" class="com.sparrow.facade.initializer.SparrowContextInitializer"/>
    <bean name="cacheMonitor" class="com.sparrow.redis.SparrowCacheMonitor"/>

    <bean name="poolConfig" class="redis.clients.jedis.JedisPoolConfig">
        <property name="maxActive" value="200"/>
        <property name="maxIdle" value="1"/>
        <property name="maxWait" value="2"/>
        <property name="minIdle" value="3"/>
        <property name="testOnBorrow" value="false"/>
        <property name="timeBetweenEvictionRunsMillis" value="10000"/>
        <property name="minEvictableIdleTimeMillis" value="1800000"/>
    </bean>

    <bean name="redisPool" class="com.sparrow.cache.impl.redis.RedisPool">
        <property name="urls" value="127.0.0.1:6379"/>
        <property name="config" ref="poolConfig"/>
        <property name="cacheMonitor" ref="cacheMonitor"/>
    </bean>

    <bean name="cacheClient" class="com.sparrow.cache.impl.redis.RedisCacheClient">
        <property name="redisPool" ref="redisPool"/>
    </bean>


    <bean name="distributionLock" class="com.sparrow.concurrent.DistributionLock">
        <constructor-arg index="1" name="cacheClient" ref="cacheClient"/>
        <constructor-arg index="2"  name="lockKey" value="LOCK:BUSINESS"/>
        <constructor-arg index="3" type="java.lang.Integer" name="expireSecs" value="10"/>
    </bean>
</beans>

=== sparrowzoo/sparrow-shell/demo/sparrow-test/src/test/resources/redis_cluster_config.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!--
  ~ Licensed to the Apache Software Foundation (ASF) under one or more
  ~ contributor license agreements.  See the NOTICE file distributed with
  ~ this work for additional information regarding copyright ownership.
  ~ The ASF licenses this file to You under the Apache License, Version 2.0
  ~ (the "License"); you may not use this file except in compliance with
  ~ the License.  You may obtain a copy of the License at
  ~
  ~     http://www.apache.org/licenses/LICENSE-2.0
  ~
  ~ Unless required by applicable law or agreed to in writing, software
  ~ distributed under the License is distributed on an "AS IS" BASIS,
  ~ WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  ~ See the License for the specific language governing permissions and
  ~ limitations under the License.
  -->

<!DOCTYPE beans PUBLIC "-//sparrow Framework//DTD ioc Configuration//EN"
        "beans.dtd">
<beans>
    <bean name="initializer" class="com.sparrow.facade.initializer.SparrowContextInitializer"/>
    <bean name="cacheMonitor" class="com.sparrow.redis.SparrowCacheMonitor"/>

    <bean name="poolConfig" class="org.apache.commons.pool2.impl.GenericObjectPoolConfig">
        <property name="maxActive" value="5"/>
        <property name="maxIdle" value="1"/>
        <property name="maxWait" value="2"/>
        <property name="minIdle" value="3"/>
        <property name="testOnBorrow" value="false"/>
        <property name="timeBetweenEvictionRunsMillis" value="10000"/>
        <property name="minEvictableIdleTimeMillis" value="1800000"/>
    </bean>

    <bean name="redisPool" class="com.sparrow.cache.impl.redis.lettuce.RedisPool">
        <property name="urls" value="redis://10.2.2.13:8030/2"/>
        <property name="cacheMonitor" ref="cacheMonitor"/>
        <property name="config" ref="poolConfig"/>
    </bean>

    <bean name="cacheClient" class="com.sparrow.cache.impl.redis.lettuce.RedisCacheClient">
        <property name="redisPool" ref="redisPool"/>
    </bean>
</beans>
